export const CANVAS_WIDTH = 1400

export const NAME_HEIGHT = 120
export const SECOND_ROW_HEIGHT = 180
export const COMMUNICATION_ROW_HEIGHT = 240
export const BOTTOM_ROW_HEIGHT = 120

export const INBOUND_COMMUNICATION_WIDTH = CANVAS_WIDTH / 2
export const OUTBOUND_COMMUNICATION_WIDTH = CANVAS_WIDTH / 2

export const PURPOSE_WIDTH_RATIO = 41.67
export const STRATEGIC_CLASSIFICATION_WIDTH_RATIO = 41.67
export const DOMAIN_ROLES_WIDTH_RATIO = 16.66

export const PURPOSE_WIDTH = Math.round(CANVAS_WIDTH * (PURPOSE_WIDTH_RATIO / 100))
export const STRATEGIC_CLASSIFICATION_WIDTH = Math.round(CANVAS_WIDTH * (STRATEGIC_CLASSIFICATION_WIDTH_RATIO / 100))
export const DOMAIN_ROLES_WIDTH = Math.round(CANVAS_WIDTH * (DOMAIN_ROLES_WIDTH_RATIO / 100))

export const ASSUMPTIONS_WIDTH = PURPOSE_WIDTH
export const VERIFICATION_METRICS_WIDTH = STRATEGIC_CLASSIFICATION_WIDTH
export const OPEN_QUESTIONS_WIDTH = DOMAIN_ROLES_WIDTH
