export enum DomainRoleType {
  SPECIFICATION_MODEL = 'specification-model',
  EXECUTION_MODEL = 'execution-model',
  ANALYSIS_MODEL = 'analysis-model',
  APPROVER = 'approver',
  ENFORCER = 'enforcer',
  OCTOPUS_ENFORCER = 'octopus-enforcer',
  INTERCHANGER = 'interchanger',
  GATEWAY = 'gateway',
  GATEWAY_INTERCHANGE = 'gateway-interchange',
  DOGFOOD_CONTEXT = 'dogfood-context',
  BUBBLE_CONTEXT = 'bubble-context',
  AUTONOMOUS_BUBBLE = 'autonomous-bubble',
  BRAIN_CONTEXT = 'brain-context',
  FUNNEL_CONTEXT = 'funnel-context',
  ENGAGEMENT_CONTEXT = 'engagement-context',
  OTHER = 'other',
}

export const DOMAIN_ROLE_LABELS: Record<DomainRoleType, string> = {
  [DomainRoleType.SPECIFICATION_MODEL]: 'Specification Model',
  [DomainRoleType.EXECUTION_MODEL]: 'Execution Model',
  [DomainRoleType.ANALYSIS_MODEL]: 'Analysis Model',
  [DomainRoleType.APPROVER]: 'Approver',
  [DomainRoleType.ENFORCER]: 'Enforcer',
  [DomainRoleType.OCTOPUS_ENFORCER]: 'Octopus Enforcer',
  [DomainRoleType.INTERCHANGER]: 'Interchanger',
  [DomainRoleType.GATEWAY]: 'Gateway',
  [DomainRoleType.GATEWAY_INTERCHANGE]: 'Gateway Interchange',
  [DomainRoleType.DOGFOOD_CONTEXT]: 'Dogfood Context',
  [DomainRoleType.BUBBLE_CONTEXT]: 'Bubble Context',
  [DomainRoleType.AUTONOMOUS_BUBBLE]: 'Autonomous Bubble',
  [DomainRoleType.BRAIN_CONTEXT]: 'Brain Context',
  [DomainRoleType.FUNNEL_CONTEXT]: 'Funnel Context',
  [DomainRoleType.ENGAGEMENT_CONTEXT]: 'Engagement Context',
  [DomainRoleType.OTHER]: 'Other',
}

export const DOMAIN_ROLE_DESCRIPTIONS: Record<DomainRoleType, string> = {
  [DomainRoleType.SPECIFICATION_MODEL]:
    'Produces a document describing a job/request that needs to be performed (e.g., Advertising Campaign Builder)',
  [DomainRoleType.EXECUTION_MODEL]: 'Performs or tracks a job (e.g., Advertising Campaign Engine)',
  [DomainRoleType.ANALYSIS_MODEL]: 'Monitors the execution (e.g., Advertising Campaign Analyser)',
  [DomainRoleType.APPROVER]: 'Receives requests and determines if they should progress to the next step',
  [DomainRoleType.ENFORCER]: 'Ensures that other contexts carry out certain operations (e.g., GDPR Context)',
  [DomainRoleType.OCTOPUS_ENFORCER]: 'Ensures that multiple/all contexts in the system all comply with a standard rule',
  [DomainRoleType.INTERCHANGER]: 'Translates between multiple ubiquitous languages',
  [DomainRoleType.GATEWAY]: 'Sits at the edge of a system and manages inbound and/or outbound communication',
  [DomainRoleType.GATEWAY_INTERCHANGE]: 'Combines gateway and interchange functionality',
  [DomainRoleType.DOGFOOD_CONTEXT]: 'Simulates the customer experience of using the core bounded contexts',
  [DomainRoleType.BUBBLE_CONTEXT]: 'Sits in-front of legacy contexts providing a new, cleaner model',
  [DomainRoleType.AUTONOMOUS_BUBBLE]: 'Bubble context with independent data store and asynchronous synchronization',
  [DomainRoleType.BRAIN_CONTEXT]: 'Contains a large number of important rules (likely anti-pattern)',
  [DomainRoleType.FUNNEL_CONTEXT]: 'Receives documents from multiple upstream contexts and standardizes them',
  [DomainRoleType.ENGAGEMENT_CONTEXT]: 'Provides key features which attract users to keep using the product',
  [DomainRoleType.OTHER]: 'Custom role type',
}
